### ISSUE TITLE
Possible typo in sort example

### ISSUE THREAD

**Issue by andresn** [biodataprog/GEN220_2020#1]
@hyphaltip please correct me if I'm wrong, but I think the command is (diff: -k3,3 vs. -k3,1):
`sort -k3,3nr yeast_orfs-to-chr1.FASTA.tab | cut -f1,3 |  head -n 5`
For this part of [your walk through](https://biodataprog.github.io/GEN220_2020/UNIX/02_Analysis_summary):
<img width="665" alt="image" src="https://user-images.githubusercontent.com/69597/95666885-4384e880-0b13-11eb-897e-c59e36a00c17.png">

Here are the diff outputs I get respectively:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/69597/95666873-10425980-0b13-11eb-8436-eaa00d42cb05.png">

And my apologies in advance if this came up already!

**Comment by hyphaltip** [comment]
Thanks andres. have fixed now and add more documentation.

**Comment by hyphaltip** [comment]
This is resolved now.
